export const MEMBERS_LOADED = "MEMBERS_LOADED";
export const MEMBER_LOADED = "MEMBER_LOADED";
export const MEMBERS_BY_NAME = "MEMBERS_BY_NAME";
export const FETCH_RESOURCES_FAIL = "FETCH_RESOURCES_FAIL";